import { VerticalBox, LineEdit, ListView, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    full-screen: false;

    in-out property <[string]> todo-items: [];
    in-out property <string> new-item: "";
    in property <bool> use-gradient: true;

    callback add-item(string);
    callback remove-item(int);

    title: "ToDo";
    icon: @image-url("img/todo-logo.svg");
    background: use-gradient ? @linear-gradient(
        90deg,
        #5c56d6 0%,
        #7256d6 33%,
        #ab34eb 55%,
        #d334eb 77%,
        #e834eb 100%
    ) : #000;
    GridLayout {
        padding: 33px;
        spacing: 10px;
        Row {
            Text {
                text: "To-Do List";
                horizontal-alignment: center;
                font-size: 50px;
                font-family: "Copperplate";
                font-weight: 700;
                color: black;
            }
        }
        Row {
            HorizontalBox {
                LineEdit {
                    placeholder-text: "Enter your task...";
                    horizontal-alignment: center;
                    font-size: 25px;
                    height: 45px;
                    width: 450px;
                    padding: 20px;
                    opacity: 0.8;

                    text <=> root.new-item;

                    accepted => {
                        root.add-item(self.text);
                    }

                }
            }
        }
        Row {
            VerticalBox {
                Rectangle {
                    border-color: black;
                    border-width: 2px;
                    border-radius: 12px;
                    height: 500px;
                    width: 450px;
                    ListView {
                        width: 450px;
                        padding: 10px;
                        for todo[idx] in root.todo-items: Rectangle {
                            background: Math.mod(idx, 2) == 0 ? #ffffff0f : #ffffff40;
                            border-radius: 8px;
                            HorizontalBox {
                                padding: 12px;
                                TouchArea {
                                   Rectangle {
                                       background: transparent;
                                       Text {
                                           font-size: 24px;
                                           font-weight: 100;
                                           text: todo;
                                           color: black;
                                       }
                                   }
                                   clicked => { root.remove-item(idx); }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}